"""add models

Revision ID: 451fbc57651f
Revises: 
Create Date: 2023-05-24 22:46:13.605761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451fbc57651f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_group',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('problem',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['problem_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_case',
    sa.Column('problem_id', sa.BigInteger(), nullable=True),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_case')
    op.drop_table('problem')
    op.drop_table('problem_group')
    # ### end Alembic commands ###
